theme: jekyll-theme-minimal
title: "DIFFERENT TURTLE"
description: "Uma associação boa cmó diabe!"
logo: ./assets/img/logo.png
show_downloads: false
hasLinks: true
links:
  [
    { url: ./contactos.html, name: "Contactos" },
    { url: ./equipa.html, name: "Equipa" },
    { url: ./contactos.html, name: "Contactos" },
  ]
