# Site settings
title: "DIFFERENT TURTLE"
description: "Uma associação boa cmó diabe!"
logo: ./assets/img/logo.png
show_downloads: false
hasLinks: true
email:
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

facebook_page: 
github_username:

# Build settings
markdown: kramdown

# description: > # this means to ignore newlines until "baseurl:"
# theme: jekyll-theme-minimal
# links:
#   [
#     { url: ./equipa.html, name: "Equipa" },
#     { url: ./missao.html, name: "Missão" },
#     { url: ./contactos.html, name: "Contactos" },
#     { url: ./blog.html, name: "Blog" },
#   ]
