# Site settings
theme: 
title: "DIFFERENT TURTLE"
description: "Uma associação boa cmó diabe!"
email:
logo: ./assets/img/logo.png
show_downloads: false
hasLinks: true
links:
  [
    { url: "#about", name: "Sobre" },
    { url: "#services", name: "Serviços" },
    { url: "#portfolio", name: "Portfolio" },
    { url: "#contact", name: "Contactos" },
    { url: "./missao.html", name: "Missão" },
    { url: "./contactos.html", name: "Contactos" },
    { url: "./blog.html", name: "Blog" },
  ]
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

facebook_page: 
github_username:

# Build settings
markdown: kramdown

# description: > # this means to ignore newlines until "baseurl:"

