theme: jekyll-theme-minimal
title: "DIFFERENT TURTLE"
description: "A MoshBit Gaming é um site informativo e independente que se foca na indústria dos videojogos."
logo: ./assets/img/logo.png
show_downloads: false
isLinks: true
link: ./assets/img/logo.png
linkName: "Link catita"